- name: Install wazuh agent
  ansible.builtin.packages:
    name:
      - wazuh-agent

- name: Configure wazuh
  ansible.builtin.copy:
    src: ossec.conf
    dest: /var/ossec/etc/ossec.conf
    owner: root

- name: Start wazuh Agent
  ansible.builtin.systemd:
    name: wazuh-agent
    state: started
    enabled: true
