[Login_Failures]
acceleration = true
acceleration.earliest_time = -1d
acceleration.hunk.dfs_block_size = 0

[Remote_Access_Authentication]
acceleration = true
acceleration.hunk.dfs_block_size = 0

[User_Detail]
acceleration = true
acceleration.cron_schedule = */1 * * * *
acceleration.hunk.dfs_block_size = 0

[Group_Policy]
acceleration = true
acceleration.cron_schedule = */1 * * * *
acceleration.earliest_time = -1w
acceleration.hunk.dfs_block_size = 0
