# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    labels:
      - docker
      - dependabot
    reviewers:
      - "dsiemienas03"
    assignees:
      - "dsiemienas03"

  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/config/" # Location of package manifests
    schedule:
      interval: "daily"
    labels:
      - pip
      - dependabot
    reviewers:
      - "dsiemienas03"
    assignees:
      - "dsiemienas03"

  - package-ecosystem: "gitsubmodule"
    directory: "/submodules/" # Location of package manifests
    schedule:
      interval: "daily"
    labels:
      - gitsubmodule
      - dependabot
    reviewers:
      - "dsiemienas03"
    assignees:
      - "dsiemienas03"

  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    labels:
      - github_actions
      - dependabot
    reviewers:
      - "dsiemienas03"
    assignees:
      - "dsiemienas03"
