- name: Initialize new machines
  hosts: "firewall"
  connection: local

  vars:
    provider:
      ip_address: "{{ ip_address }}"
      api_key: "{{ api_key }}"
  collections:
    paloaltonetworks.panos

  tasks:

# Basic setup
  # Set up VLANs
    - name: Create VLAN
      paloaltonetworks.panos.panos_vlan:
        provider: '{{ provider }}'
        name: 'default'
  # Set up interfaces
    - name: wan
      paloaltonetworks.panos.panos_zone:
        provider: '{{ provider }}'
        mode: 'layer2'
        zone: 'wan'
    - name: lan
      paloaltonetworks.panos.panos_zone:
        provider: '{{ provider }}'
        mode: 'layer2'
        zone: 'lan'
    # - name: add ethernet1/1 to zone wan
    #   paloaltonetworks.panos.panos_interface:
    #     provider: '{{ provider }}'
    #     mode: 'layer2'
    #     vlan_name: 'default'
    #     zone_name: 'wan'
    #     if_name: "ethernet1/1"
    #     gathered_filter: 'if_name'
    # - name: add ethernet1/2 to zone lan
    #   paloaltonetworks.panos.panos_interface:
    #     provider: '{{ provider }}'
    #     mode: 'layer2'
    #     vlan_name: 'default'
    #     zone_name: 'lan'
    #     if_name: 'ethernet1/2'
    #     gathered_filter: 'if_name'
    - name: Update VLAN
      paloaltonetworks.panos.panos_vlan:
        provider: '{{ provider }}'
        name: 'default'
        interface:
          - 'ethernet1/1'
          - 'ethernet1/2'

# Add a few basic objects
    - name: Add DNS address group
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ provider }}"
        name: "DNS"
        value: "8.8.8.8" # Add local DNS server here

# log stuff
    - name: Create syslog server
      paloaltonetworks.panos.panos_syslog_server:
        provider: '{{ provider }}'
        syslog_profile: 'my-profile'
        name: 'my-syslog-server'
        server: '10.1.1.1'
        syslog_port: 514
    - name: Create log forwarding profile
      paloaltonetworks.panos.panos_log_forwarding_profile:
        provider: '{{ provider }}'
        name: 'Loggie McLog Face'
        enhanced_logging: true

# INBOUND RULES
  # Add base rules for http
    - name: inbound-http1
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "inbound-http-1"
        source_zone: ["wan"]
        source_ip: ["any"]
        destination_zone: ["lan"]
        destination_ip: ["any"]
        service: 'service-http'
        action: "allow"

    - name: inbound-http2
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "inbound-http2"
        source_zone: ["wan"]
        source_ip: ["any"]
        destination_zone: ["lan"]
        destination_ip: ["any"]
        service: 'service-http'
        action: "allow"

    - name: inbound-http3
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "inbound-http3"
        source_zone: ["wan"]
        source_ip: ["any"]
        destination_zone: ["lan"]
        destination_ip: ["any"]
        service: 'service-http'
        action: "allow"
    - name: inbound-http4
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "inbount-http4"
        source_zone: ["wan"]
        source_ip: ["any"]
        destination_zone: ["lan"]
        destination_ip: ["any"]
        service: 'service-http'
        action: "allow"

    - name: inbound-http5
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "inbount-http5"
        source_zone: ["wan"]
        source_ip: ["any"]
        destination_zone: ["lan"]
        destination_ip: ["any"]
        service: 'service-http'
        action: "allow"

  # add base rules for ssh
    - name: inbound-ssh1
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "inbound-ssh1"
        source_zone: ["wan"]
        source_ip: ["any"]
        destination_zone: ["lan"]
        destination_ip: ["any"]
        application: ["ssh"]
        action: "allow"

    - name: inbound-ssh2
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "inbound-ssh2"
        source_zone: ["wan"]
        source_ip: ["any"]
        destination_zone: ["lan"]
        destination_ip: ["any"]
        application: ["ssh"]
        action: "allow"
    - name: inbound-ssh3
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "inbound-ssh3"
        source_zone: ["wan"]
        source_ip: ["any"]
        destination_zone: ["lan"]
        destination_ip: ["any"]
        application: ["ssh"]
        action: "allow"

  # add base rules for mail protocols
    - name: inbound-smtp
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "inbount-smtp"
        source_zone: ["wan"]
        source_ip: ["any"]
        destination_zone: ["lan"]
        destination_ip: ["any"]
        application: ["smtp"]
        action: "allow"
    - name: inbound-pop
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "inbound-pop"
        source_zone: ["wan"]
        source_ip: ["any"]
        destination_zone: ["lan"]
        destination_ip: ["any"]
        application: ["pop3"]
        action: "allow"

  # add rules for dns
    - name: inbound-dns
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "outbound-dns"
        source_zone: ["wan"]
        source_ip: ["any"]
        destination_zone: ["lan"]
        destination_ip: ["DNS"]
        application: ["dns"]
        action: "allow"

# OUTBOUND rules
  # DNS
    - name: outbound-dns
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "outbound-dns"
        source_zone: ["wan"]
        source_ip: ["any"]
        destination_zone: ["lan"]
        destination_ip: ["DNS"]
        application: ["dns"]
        action: "allow"
    - name: outbound-dns2
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "outbound-dns2"
        source_zone: ["wan"]
        source_ip: ["any"]
        destination_zone: ["lan"]
        destination_ip: ["DNS"]
        application: ["dns"]
        action: "allow"

    - name: outbound-http
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "outbound-http"
        source_zone: ["lan"]
        source_ip: ["any"]
        destination_zone: ["wan"]
        destination_ip: ["any"]
        service: 'service-http'
        action: "allow"

    - name: outbound-https
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "outbound-https"
        source_zone: ["lan"]
        source_ip: ["any"]
        destination_zone: ["wan"]
        destination_ip: ["any"]
        service: ["service-http", "service-https"]
        action: "allow"

# Allow all traffic
    - name: Allow all traffic in
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "inbound-all"
        source_zone: ["any"]
        source_ip: ["any"]
        destination_zone: ["lan"]
        destination_ip: ["any"]
        application: ["any"]
        action: "allow"

    - name: Allow all traffic out
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "outbound-all"
        source_zone: ["lan"]
        source_ip: ["any"]
        destination_zone: ["any"]
        destination_ip: ["any"]
        application: ["any"]
        action: "allow"
