---
- name: snapshot | List all existing virtual machines on node
  community.general.proxmox_vm_info:
    api_host: "{{ ip_address }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ api_password }}"
    node: "{{ node }}"

- name: snapshot | Create new container snapshot
  community.general.proxmox_snap:
    api_host: "{{ ip_address }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ api_password }}"
    vmid: "{{ add_vm }}"
    state: present
    snapname: "{{ vm_id }}-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}"
