---
- name: certs | Configure Palo Certs
  paloaltonetworks.panos.panos_cert_gen_ssh:
    # provider: "{{ provider }}"
    key_filename: test
    ip_address: "{{ inventory_hostname }}"
    username: admin
    cert_cn: Palo
    cert_friendly_name: palo_ssh
    signed_by: root-ca
