---
- name: content_update | Check latest content
  # Get an updated dynamic content list
  paloaltonetworks.panos.panos_op:
    provider: "{{ provider }}"
    cmd: "request content upgrade check"
  register: check

- name: content_update | Get content info
  # Get the current content version
  paloaltonetworks.panos.panos_op:
    provider: "{{ provider }}"
    cmd: request content upgrade info
  register: info

- name: content_update | Set fact for parsed JSON data
  ansible.builtin.set_fact:
    parsed_data: "{{ info.stdout | from_json }}"

- name: content_update | Extract relevant details from parsed data
  ansible.builtin.set_fact:
    content_updates: >-
      {{ parsed_data.response.result['content-updates'].entry
      | map(attribute='version')
      | list }}
    downloaded_updates: >-
      {{ parsed_data.response.result['content-updates'].entry
      | selectattr('downloaded', 'equalto', 'yes')
      | map(attribute='version')
      | list }}
    current_update: >-
      {{ parsed_data.response.result['content-updates'].entry
      | selectattr('current', 'equalto', 'yes')
      | map(attribute='version')
      | first
      | default() }}
    latest_update: >-
      {{ parsed_data.response.result['content-updates'].entry
      | sort(attribute='released-on', reverse=True)
      | map(attribute='version')
      | first }}

- name: content_update | Show extracted data
  ansible.builtin.debug:
    msg:
      - "All Versions: {{ content_updates }}"
      - "Downloaded Versions: {{ downloaded_updates }}"
      - "Current Version: {{ current_update }}"
      - "Latest Version: {{ latest_update }}"
      - "Need to download: {{ (latest_update != current_update) }}"

- name: content_update | Download and Install
  when: (latest_update != current_update)
  block:
    - name: content_update | Download latest content
      # Download the latest version
      ansible.builtin.debug:
        msg: "Download latest content"
    - name: content_update | Download latest content
      # Download the latest version
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: request content upgrade download latest
      register: download

    - name: content_update | Content update result
      ansible.builtin.debug:
        msg:
          - JobID: "{{ (download.stdout | from_json).response.result.job }}"

    - name: content_update | Check content download result
      # wait for this job to finish
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: show jobs id {{ (download.stdout | from_json).response.result.job }}
      register: download_job
      until: download_job is not failed and (download_job.stdout | from_json).response.result.job.status == 'FIN'
      retries: 150
      delay: 2

    - name: content_update | Install latest content
      # Content is downloaded and ready, now install it
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: request content upgrade install version latest
      register: install

    - name: content_update | Content update result
      ansible.builtin.debug:
        msg: "{{ install.stdout }}"

    - name: content_update | Check content install result
      # again, wait for job to complete
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: show jobs id {{ (install.stdout | from_json).response.result.job }}
      register: install_job
      until: install_job is not failed and (install_job.stdout | from_json).response.result.job.status == 'FIN'
      retries: 150
      delay: 2

    - name: content_update | Content update result
      ansible.builtin.debug:
        msg: "{{ install_job.stdout }}"
