---
# Config vars
# palo_update_os: false
# palo_config_update_other: false
# palo_config_zones: true
# palo_config_initial_interface: true
# palo_config_initial_groups: true
# palo_config_logging: true
# palo_config_initial_rules: true
# palo_panos_version: 11.1.2
