---
- name: ESXI snapshot
  hosts: esxi
  ignore_errors: true
  gather_facts: false
  roles:
    - dsu.ccdc.esxi
  vars:
    esxi_user: root
  # strategy: free

  tasks:
    - name: Create vSwitch
      when: esxi_vswitches is defined
      # ansible.builtin.debug:
      #   msg: "{{ new_net }}"
      ansible.builtin.include_role:
        name: dsu.ccdc.esxi
        tasks_from: vswitch
      loop: "{{ esxi_vswitches }}"
      loop_control:
        loop_var: new_net
