---
- name: PfSense rules
  hosts: pfsense
  connection: local
  ignore_errors: true
  roles:
    - dsu.ccdc.pfsense
  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: dsu.ccdc.pfsense
        vars_from: main.yml

    - name: Import vars
      ansible.builtin.include_vars:
        dir: /home/ansible/vars/

    - name: Add Critical rules
      ansible.builtin.import_role:
        name: dsu.ccdc.pfsense
        tasks_from: pfsense_critical
        vars_from: main.yml

    - name: Firewall rules
      when: service.key not in fw_block
      ansible.builtin.include_role:
        name: dsu.ccdc.pfsense
        tasks_from: pfsense_service
        vars_from: main.yml
      loop: "{{ services.pfsense | dict2items }}"
      loop_control:
        loop_var: service
