---
- name: Firewall rules
  hosts: wrccdc_fw
  # connection: local
  ignore_errors: true
  gather_facts: false
  tasks:
    - name: Import vars
      ansible.builtin.include_vars:
        dir: /home/ansible/vars/

    - name: Set base FW rules
      ansible.builtin.import_role:
        name: dsu.ccdc.wasabi_wall
        tasks_from: wasabi_base

    - name: Set service FW rules
      ansible.builtin.include_role:
        name: dsu.ccdc.wasabi_wall
        tasks_from: wasabi_svc
      loop: "{{ services.wrccdc_fw | dict2items }}"
      loop_control:
        loop_var: service

    - name: Block services
      when: services.wr_block is defined
      ansible.builtin.include_role:
        name: dsu.ccdc.wasabi_wall
        tasks_from: wasabi_block
      loop: "{{ services.wr_block | dict2items }}"
      loop_control:
        loop_var: service

    - name: Set base FW rules
      ansible.builtin.import_role:
        name: dsu.ccdc.wasabi_wall
        tasks_from: wasabi_base
