- name: Inbound-icmp
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-icmp"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["ping"]
    action: "allow"
    log_start: true
    log_end: true
    group_profile: "security"

- name: Inbound-rdp
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-rdp"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["windows"]
    application: ["ms-rdp"]
    action: "allow"
    log_start: true
    log_end: true
    group_profile: "security"

- name: Inbound-sql
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-sql"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["mysql"]
    action: "deny"
    log_start: true
    log_end: true
    group_profile: "security"

- name: outbound-ccs
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "outbound-ccs"
    source_zone: ["lan"]
    source_ip: ["any"]
    destination_zone: ["wan"]
    destination_ip: ["{{ccs}}"]
    service: "service-web"
    action: "allow"
    log_start: true
    log_end: true
    group_profile: "security"

# web-browsing
- name: Inbound-http1
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-http-1"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["web-browsing"]
    action: "allow"
    log_start: true
    log_end: true
    group_profile: "security"

- name: Inbound-http2
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-http2"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["web-browsing"]
    action: "allow"
    log_start: true
    log_end: true
    group_profile: "security"

- name: Inbound-http3
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-http3"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["web-browsing"]
    action: "allow"
    log_start: true
    log_end: true
    group_profile: "security"

- name: Inbound-http4
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-http4"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["web-browsing"]
    action: "allow"
    log_start: true
    log_end: true
    group_profile: "security"

- name: Inbound-http5
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-http5"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["web-browsing"]
    action: "allow"
    log_start: true
    log_end: true
    group_profile: "security"

# add base rules for ssh
- name: Inbound-ssh1
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-ssh1"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["ssh"]
    action: "allow"
    log_start: true
    log_end: true
    group_profile: "security"

- name: Inbound-ssh2
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-ssh2"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["ssh"]
    action: "allow"
    log_start: true
    log_end: true
    group_profile: "security"

- name: Inbound-ssh3
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-ssh3"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["ssh"]
    action: "allow"
    log_start: true
    log_end: true
    group_profile: "security"

# add base rules for mail protocols
- name: Inbound-smtp
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-smtp"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["smtp"]
    action: "allow"
    log_start: true
    log_end: true
    group_profile: "security"

- name: Inbound-pop
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-pop"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["pop3"]
    action: "allow"
    log_start: true
    log_end: true
    group_profile: "security"


# add rules for dns
- name: Inbound-dns
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "outbound-dns"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["dns_local"]
    application: ["dns"]
    action: "allow"
    log_start: true
    log_end: true
    group_profile: "security"

# OUTBOUND rules
# DNS
- name: Outbound-dns
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "outbound-dns"
    source_zone: ["lan"]
    source_ip: ["any"]
    destination_zone: ["wan"]
    destination_ip: ["{{dns_white}}"]
    application: ["dns"]
    action: "allow"
    log_start: true
    log_end: true
    group_profile: "security"

- name: Outbound-dns2
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "outbound-dns2"
    source_zone: ["lan"]
    source_ip: ["any"]
    destination_zone: ["wan"]
    destination_ip: ["{{dns_white}}"]
    application: ["dns"]
    action: "allow"
    log_start: true
    log_end: true
    group_profile: "security"


# ssl, web-browsing, apt-get, ftp, sftp, pop3, ssh

- name: outbound-web
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "outbound-web"
    source_zone: ["lan"]
    source_ip: ["any"]
    destination_zone: ["wan"]
    destination_ip: ["any"]
    application: ["web-browsing", "ssl"]
    action: "allow"
    log_start: true
    log_end: true
    group_profile: "security"

- name: Outbound-filtered
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "outbound-filtered"
    source_zone: ["lan"]
    source_ip: ["any"]
    destination_zone: ["wan"]
    destination_ip: ["any"]
    application: ["apt-get"]
    action: "allow"
    log_start: true
    log_end: true
    group_profile: "security"

- name: Outbound-web-all
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "outbound-web-all"
    source_zone: ["lan"]
    source_ip: ["any"]
    destination_zone: ["wan"]
    destination_ip: ["any"]
    service: "service-web"
    action: "deny"
    log_start: true
    log_end: true
    group_profile: "security"

# Safety rule
- name: Inbound safety
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-safety"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["safe"]
    action: "deny"
    log_start: true
    log_end: true
    group_profile: "security"


# Allow all traffic
- name: Allow all traffic in
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-all"
    source_zone: ["any"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["any"]
    action: "allow"
    log_start: true
    log_end: true
    group_profile: "security"

- name: Allow all traffic out
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "outbound-all"
    source_zone: ["lan"]
    source_ip: ["any"]
    destination_zone: ["any"]
    destination_ip: ["any"]
    application: ["any"]
    action: "allow"
    log_start: true
    log_end: true
    group_profile: "security"

- name: Add windows server rules
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "lan to windows-server"
    source_zone: ["lan"]
    source_ip: ["windows"]
    destination_zone: ["winsrv"]
    destination_ip: ["winsrv"]
    application: ["winsrv-apps"]
    action: "allow"
    log_start: true
    log_end: true
    group_profile: "security"


- name: Add outbound block rule
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "outbound-block-all"
    source_zone: ["any"]
    source_ip: ["lan"]
    destination_zone: ["any"]
    destination_ip: ["any"]
    application: ["any"]
    action: "deny"
    log_start: true
    log_end: true
    group_profile: "security"

- name: Add inbound block rule
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-block-all"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["any"]
    action: "deny"
    log_start: true
    log_end: true
    group_profile: "security"



# - name: Set initial rules as done
#   set_fact:
#     config_initial_rules: "n"
#     cacheable: true