- name: Check for wildfire updated
  paloaltonetworks.panos.panos_op:
    provider: '{{ provider }}'
    cmd: 'request wildfire upgrade check'
  register: check

- name: Download latest content
  # Download the latest version
  paloaltonetworks.panos.panos_op:
    provider: '{{ provider }}'
    cmd: |
      <request><wildfire><upgrade><download>
      <latest></latest>
      </download></upgrade></wildfire></request>
    cmd_is_xml: true
  register: download
- name: Check content download result
  # wait for this job to finish
  paloaltonetworks.panos.panos_op:
    provider: '{{ provider }}'
    cmd: 'show jobs id {{ (download.stdout | from_json).response.result.job }}'
  register: download_job
  until: download_job is not failed and (download_job.stdout | from_json).response.result.job.status == 'FIN'
  retries: 20
  delay: 30

- name: Install latest content
  # Content is downloaded and ready, now install it
  paloaltonetworks.panos.panos_op:
    provider: '{{ provider }}'
    cmd: |
      <request><wildfire><upgrade><install>
      <version>latest</version>
      </install></upgrade></wildfire></request>
    cmd_is_xml: true
  register: install