enabled_modules:
  - "files_to_backup"
  - "root_password_changes"
  - "user_password_changes"
  - "audit_users"
# - enumerate services
# - change sql pass
# - change ssh settings
# - firewall
# - setup PHP
# - setup logging
files_to_backup:
  - "/etc/shadow"
  - "/etc/passwd"
  - "/etc/gshadow"
  - "/etc/group"
